version: 2

sbt-build: &sbt-build
  docker:
    - image: hseeberger/scala-sbt:8u151-2.12.4-1.1.1
  environment:
    - SBT_OPTS: "-Xms512m -Xmx2g -XX:+UseConcMarkSweepGC -XX:ReservedCodeCacheSize=256m -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -no-colors -batch"
  steps:
    - add_ssh_keys:
        fingerprints:
          - "57:c7:e7:60:94:77:3f:a4:ed:33:bb:d3:b3:b1:92:b4"
    - run: mkdir ~/.sbt/gpg
    - run: echo $PGPKEY | base64 --decode --ignore-garbage > ~/.sbt/gpg/secring.asc
    - run: gpg --batch --allow-secret-key-import --import ~/.sbt/gpg/secring.asc
    - run: git config --global user.signingkey 2A3A8E063D9FD649
    - run: git config --global user.email tech@upvest.co
    - run: git config --global user.name "Tech@Upvest"
    - checkout
    - run: git branch -u origin/$CIRCLE_BRANCH
    - setup_remote_docker:
        docker_layer_caching: true
        version: 17.09.0-ce
    - restore_cache:
        key: sbt-deps-{{ checksum "build.sbt" }}
    - run: sbt "$SBT_OPTS" "$SBT_CMDS"
    - run: rm ~/.sbt/gpg/secring.asc
    - run: rm -rf ~/.gnupg
    - save_cache:
        key: sbt-deps-{{ checksum "build.sbt" }}
        paths:
          - ~/.m2
          - ~/.ivy2
          - ~/.sbt

jobs:
  release:
    <<: *sbt-build
    resource_class: small
    environment:
      SBT_CMDS: "; release with-defaults"

  release-snapshot:
    <<: *sbt-build
    resource_class: small
    environment:
      SBT_CMDS: "; publishSigned"

  test:
    <<: *sbt-build
    resource_class: small
    environment:
      - SBT_CMDS: "; test; example"

workflows:
  version: 2

  ci:
    jobs:
      - test

  release:
    jobs:
      - release:
          filters:
            branches:
              only: master
      - release-snapshot:
          filters:
            branches:
              only: develop
